### PR TITLE
Log message if looking for specific files throw an exception, upd…

### LINKED ISSUE #99: Log a warning
if search for environment specific files throws an exception.

### PR DESCRIPTION
**Pull request by jbellmann**
…ate jacoco version to 0.8.0

fixes #99

### CODE REVIEW

File: src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java [hunk 1]
```diff
@@ -599,6 +604,8 @@ private boolean isFilesystemSecretsLayout() {
         try {
             return getCredentialsDir().list(forSuffix("-token-secret")).length > 0;
         } catch (Exception e) {
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java]: Isn't this a bit too broad? Wouldn't `FileNotFoundException` be enough?

File: src/main/java/org/zalando/stups/tokens/FileSupplier.java [hunk 2]
```diff
@@ -53,12 +55,15 @@ public static File getCredentialsDir() {
...
             if (dir == null) {
-                throw new IllegalStateException(
-                        String.format("environment variable %s not set", CREDENTIALS_DIR_PROP)
-                );
+                // to avoid some configuration on developers
+                if (new File(DEFAULT_CREDENTIALS_DIR).exists() && new File(DEFAULT_CREDENTIALS_DIR).isDirectory()) {
+                    return new File(DEFAULT_CREDENTIALS_DIR);
+                } else {
+                    throw new IllegalStateException(
+                            String.format("environment variable %s not set and default '/meta/credentials' not exists or not a directory.", CREDENTIALS_DIR_PROP));
```
Comment (otrosien) [inline src/main/java/org/zalando/stups/tokens/FileSupplier.java]: .. does not exist or is not a directory. Also: put %s and take /meta/credentials from the constant.

File: src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java (hunk 1 above)
Comment (jbellmann) [reply src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java]: No, `list()` can also throw an `SecurityException`. Furthermore, `getCredentialsDir()' throws an `IllegalStateException' when `CREDENTIALS_DIR` is not provided by user as an environment variable.
I guess that's the reason why it fails when people move from STUPS to K8s I guess. This was handled by Taupage transparently and nobody specifies it in the deployment-manifest?

Do you want me to make it more specific for these two Exceptions?
